export const PLAYER_COLORS = {
  CORAL: '#E85D5D',
  AMBER: '#D97706',
  EMERALD: '#059669',
  AZURE: '#2563EB',
  VIOLET: '#7C3AED',
  MAGENTA: '#DB2777',
}

export const PLAYER_COLOR_ORDER = ['CORAL', 'AMBER', 'EMERALD', 'AZURE', 'VIOLET', 'MAGENTA']
